### ISSUE TITLE
Hi ZjAllen

### ISSUE THREAD

**Issue by Cesc2020** [ZJAllen/ShushEngine#3]
I use Raspberry pi 2 and TMC5160 Bigtreetech
I do example.py and no work. Well sometimes the stepper turn on a bit and back
I  must use the wiring:
https://blog.trinamic.com/2018/02/19/stepper-motor-with-tmc5160/
but trinamic move the wiring and now I cant find.

I use this:
print( m.read(Motor.Register.XACTUAL))
and python return this
NameError: name 'Motor' is not defined

so I dont know if the wiring fine or I need some  python library
Can you help me?
ty in advance

**Comment by jblatcher** [comment]
Hey, I just found this library myself, I know this was over a month ago but I figured I'd answer anyway. The problem you had here was you're trying to essentially call something from a class you're not in. If you want to sue the read function you must first import the Registers and use that. However there's already a predefined function m.get_position() for retrieving the position and I would recommend just using that. So you would do print(m.get_position()) you'll also need this in a while loop if you want a constant reading.

**Comment by ZJAllen** [comment]
Hi @Cesc2020, sorry I'm just now seeing this. Yes, @jblatcher is correct, please use the m.get_position() function for reading the current position.

**Comment by Cesc2020** [comment]
Hello 
Zj
Ok
I will try . These last times with corona ate not the best. Thanks 
Best regards from spain

**Comment by ZJAllen** [comment]
@Cesc2020 definitely double check the wiring, too. I have had issues related to wiring before. Sometimes the different versions of the driver boards have different pin-outs.

**Comment by ZJAllen** [comment]
@Cesc2020 Another thing to check is the version of your motor driver board. So if you are using v1.2 board, you will not be able to use this library because that board is in Step/Dir mode only. This library requires SPI (or motion control) mode. https://github.com/bigtreetech/BIGTREETECH-TMC5160-V1.0/issues/8
