### ISSUE TITLE
 problem in connecting (m0_enable) in your documentation with TMC1560

### ISSUE THREAD

**Issue by basfari** [ZJAllen/ShushEngine#6]
Hi, first of all thank you very much for your work on this library. 

I did not understand how the pin "m0_enable" is connected in your documentation (found here: ShushEngine/shush/boards/shush_mk1.py ). 

You said that you are following the wiring on this link:
https://blog.trinamic.com/2019/03/29/internet-of-moving-things-tmc5130-raspberry-pi-3b/
There it is written that it uses the following pinouts:

RASPBERRY PI        | BOB
 --------------------------
 (17) +3V3          | VCC_IO
 (19) SPI_MOSI      | SDI
 (21) SPI_MISO      | SDO
 (23) SPI_SCK       | SCK
 (24) SPI_CE0_N     | CSN
 (25) GND           | GND

Put **connect** following pins of the BOB **to GND**, too:
CLK16 (enables internal clock)
**DRV_ENN (enables driver)**

and we have **VCC_IO is connected to +3.3 V**

Thus, your enable pin in your library (m0_enable = 2) is connected to what in TMC1560?

Many thanks in advance.

**Comment by ZJAllen** [comment]
Hey, thanks for your question. Sorry it is not more clear. If you wire per the Trinamic blog post, the enable pin will be pulled to GND, thus always enabled. In this library, if you connect the DRV_ENN pin on the driver to the Pi’s GPIO2, or any other pin of your choice, you can toggle the enabled state. 

The file at `shush/boards/shush_mk1.py` shows the enable pinout configuration. So where it says `m0_enable = 2` that corresponds to the GPIO2 pin on the [Pi](https://pinout.xyz/)
